### PR TITLE
Guard urls during a mirrorlist refresh

### LINKED ISSUE #92: Cannot sync every repo's DBs
Hello. I have been getting this error for quite some time.
If I point my repos to pacoloco and then point pacoloco to my mirror list, only some of the DBs get downloaded.
On the other DBs I get:
 ``` pacoloco.go:168: repo archlinux has no urls ```

docker-compose.yml
```yml
---
version: "3.8"
services:
  pacoloco:
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    ports:
      - "9129:9129"
    volumes:
      - /pacoloco/cache:/var/cache/pacoloco
      - /pacoloco/pacoloco.yaml:/etc/pacoloco.yaml
      - /etc/pacman.d/reflector-mirrorlist:/etc/mirrorlist
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
```

/pacoloco/pacoloco.yaml (mapped to /etc/pacoloco.yaml inside the container)
```yml
port: 9129
cache_dir: /var/cache/pacoloco
purge_files_after: 360000
download_timeout: 3600
repos:
  archlinux:
    mirrorlist: /etc/mirrorlist
user_agent: Pacoloco/1.2
prefetch:
  cron: 0/30 * * * * 
  ttl_unaccessed_in_days: 30 
  ttl_unupdated_in_days: 300 
  ```

/etc/pacman.d/reflector-mirrorlist (mapped to /etc/mirrorlist inside the container)
```
Server = https://mirrors.celianvdb.fr/archlinux/$repo/os/$arch
Server = https://archlinux.mailtunnel.eu/$repo/os/$arch
Server = https://mirror.theo546.fr/archlinux/$repo/os/$arch
Server = https://mirror.ubrco.de/archlinux/$repo/os/$arch
Server = https://mirror.sunred.org/archlinux/$repo/os/$arch
Server = https://mirror.cyberbits.eu/archlinux/$repo/os/$arch
Server = https://packages.oth-regensburg.de/archlinux/$repo/os/$arch
Server = https://mirror.pseudoform.org/$repo/os/$arch
Server = https://de.arch.mirror.kescher.at/$repo/os/$arch
Server = https://arch.jensgutermuth.de/$repo/os/$arch
Server = https://arch.unixpeople.org/$repo/os/$arch
Server = https://mirror.iusearchbtw.nl/$repo/os/$arch
Server = https://mirror.f4st.host/archlinux/$repo/os/$arch
Server = https://mirrors.xtom.de/archlinux/$repo/os/$arch
Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
Server = https://mirrors.janbruckner.de/archlinux/$repo/os/$arch
Server = https://mirror.cmt.de/archlinux/$repo/os/$arch
Server = https://mirrors.n-ix.net/archlinux/$repo/os/$arch
Server = https://arch.phinau.de/$repo/os/$arch
Server = https://archlinux.thaller.ws/$repo/os/$arch
```

/etc/pacman.d/mirrorlist
```Server = http://localhost:9129/repo/archlinux/$repo/os/$arch```

/etc/pacman.conf
(the important parts)
```
SigLevel    = Required DatabaseNever
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
```

Pacoloco logs (in this case core.db isn't being downloaded)
```
pacoloco.go:168: repo archlinux has no urls

downloader.go:102: downloading https://mirrors.celianvdb.fr/archlinux//extra/os/x86_64/extra.db

downloader.go:102: downloading https://mirrors.celianvdb.fr/archlinux//multilib/os/x86_64/multilib.db

pacoloco.go:270: serving cached file for archlinux/multilib/os/x86_64/multilib.db
```

As you can see, it says ```repo archlinux has no urls```

Pacman logs
```
:: Synchronizing package databases...
 core.db failed to download
 extra is up to date
 multilib is up to date
 chaotic-aur is up to date
error: failed retrieving file 'core.db' from localhost:9129 : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
```

It all works if I specify individual repos for each arch repo inside the pacoloco config, like this:

```
repos:
  core:
    mirrorlist: /etc/mirrorlist
  extra:
    mirrorlist: /etc/mirrorlist
  multilib:
    mirrorlist: /etc/mirrorlist
```
and then change my /etc/pacman.conf to have this instead

```
[core]
Server = http://localhost:9129/repo/core/$repo/os/$arch

[extra]
Server = http://localhost:9129/repo/extra/$repo/os/$arch

[multilib]
Server = http://localhost:9129/repo/multilib/$repo/os/$arch
```

Thanks :)

### PR DESCRIPTION
**Pull request by krameler**
This PR tries to fix #92, by locking access to the Mirrorlist's Urls during refresh.

I had the same problem on my deployed `pacoloco` and also successfully reproduced the issue using @chennin's script. Using this PR, both were unable to reproduce the error on my system.

I'm new to go and it's concurrency model, but my guess is that the `repo archlinux has no urls` error happens due to a race condition in `getMirrorlistURLs()`:
While the Mirrorlist File is read for the first time (e.g. because of a request for 'core.db') the `URLs` array is still empty but `LastMirrorlistCheck` is already set. When in this moment the function is called concurrently (e.g. because of a parallel download request for 'extra.db') it returns the still empty `URLs` array due to a recent `LastMirrorlistCheck`, instead of waiting for it to be populated.

I used a mutex instead of setting the `LastMirrorlistCheck` after `URLs` is populated to block multiple goroutines from reading and parsing the same Mirrorlist simultaneously.
However this doesn't fix any possible racing with `reflector` or similar.

Would love for someone to try reproducing #92 with this PR on their system and review my first work with go.

### CODE REVIEW

File: urls.go [hunk 1]
```diff
@@ -48,7 +48,17 @@ func (r *Repo) getMirrorlistURLs() ([]string, error) {
 		return r.URLs, nil
 	}
 
-	r.LastMirrorlistCheck = time.Now()
+	r.MirrorlistMutex.Lock()
+	defer r.MirrorlistMutex.Unlock()
+
+	// Test time again in case another routine already checked in the meantime
+	if time.Since(r.LastMirrorlistCheck) < 5*time.Second {
```
Comment (anatol) [inline urls.go:55]: `5*time.Second` repeats twise, let's move it to a constant with human readable name.

**Comment by anatol** [comment]
The PR looks good to me. I'll test it a bit and then merge, unless there are objections.

File: urls.go (hunk 1 above)
Comment (krameler) [reply urls.go:55]: Sure

**Comment by anatol** [comment]
Thank you @krameler for your work. The PR has landed `mastrer` branch.
